spring:
  datasource:
    url: jdbc:h2:mem:expenses;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope: openid, profile, email
  h2:
    console:
      enabled: true          
server:
  port: 8080

# Google OAuth placeholders - fill in with real values

