CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 6) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    oauth_id VARCHAR(255),
    role VARCHAR(50) NOT NULL
);

CREATE TABLE groups_tbl (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE memberships (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) PRIMARY KEY,
    user_id INT NOT NULL,
    group_id INT NOT NULL
);

INSERT INTO users (id, name, email, oauth_id, role) VALUES (1, 'Alice', 'alice@example.com', 'oauth-alice', 'USER');
INSERT INTO users (id, name, email, oauth_id, role) VALUES (2, 'Bob', 'bob@example.com', 'oauth-bob', 'USER');
INSERT INTO users (id, name, email, oauth_id, role) VALUES (3, 'Reed', 'reed@example.com', 'oauth-reed', 'USER');
INSERT INTO users (id, name, email, oauth_id, role) VALUES (4, 'Jack', 'jack@example.com', 'oauth-jack', 'USER');
INSERT INTO users (id, name, email, oauth_id, role) VALUES (5, 'Admin', 'admin@example.com', 'oauth-admin', 'ADMIN');

INSERT INTO groups_tbl (id, name) VALUES (1, 'Friends');
INSERT INTO memberships (id, user_id, group_id) VALUES (1, 1, 1);
INSERT INTO memberships (id, user_id, group_id) VALUES (2, 2, 1);
